### ISSUE TITLE
Request to fix documentation link in inquirer PYPI page

### ISSUE THREAD

**Issue by kdipippo** [magmax/python-inquirer#514] opened 2024-01-26 15:36 UTC
Hello! Thank you for building this tool. I use it all the time for my scripting so that I don't have to remember to update a bunch of consts at the top of my files. It's been very helpful.

Hopefully this is something that could be remedied with another release. The "documentation" link on the pypi.org page https://pypi.org/project/inquirer/ links to https://magmax.org/python-inquirer. It would be useful to switch it to the documentation link that appears in the README here: https://python-inquirer.readthedocs.io/en/latest/.

I think the code change is switching the URL on these two lines; unsure if there is another location that also needs the swap:
- https://github.com/magmax/python-inquirer/blob/8bda8db9c3f7442f08b9683cc9a4b0e2fdc1ba36/CONTRIBUTING.md?plain=1#L102
- https://github.com/magmax/python-inquirer/blob/8bda8db9c3f7442f08b9683cc9a4b0e2fdc1ba36/pyproject.toml#L10

Thanks!

**Comment by Cube707** [comment] 2024-01-26 15:42
Duplicate of #338

**Comment by Cube707** [comment] 2024-01-26 15:48
my bad, the Issue I was thinking of is already closed. So you are completely right and this should be fixed.

Do you want to open a PR for that?

**Closed** 2024-01-29 13:56 UTC
Labels: documentation
