### ISSUE TITLE
Tuples as list choices no longer works as expected with v3.2.2 - regression from v3.2.1

### ISSUE THREAD

**Issue by dns13** [magmax/python-inquirer#515] opened 2024-01-29 12:56 UTC
The following example prints the integer part of the selected entry with v3.2.1 but the string entry in v3.2.2. I think this is a regression and not working as expected.

```python
import inquirer

entries = [
	("one", 1),
	("two", 2),
	("three", 3)
]

questions = [
	inquirer.List('device', message="test", choices=entries),
]

answers = inquirer.prompt(questions)

print(answers['device'])
```

With v3.2.1: `2`
With v3.2.2: `two`

**Comment by Cube707** [comment] 2024-01-29 13:16
Moin!,

the `str` and `repr` have always been different for `TaggedValue` pairs, one is the value and one the tag. But this shouldn't have chnanged. I will investigate.

**Comment by Cube707** [comment] 2024-01-29 13:48
yes it seems to be regression and will be fixed

**Comment by dns13** [comment] 2024-01-29 13:53
Thank you!

**Closed** 2024-01-29 14:03 UTC
Labels: bug

**Comment by Zereges** [comment] 2024-02-03 16:11
There's still issue if the second element of the tuple is `dict`. In 3.2.1 it worked:
```
>>> import inquirer
>>> test = [('aa', {'a': 1}), ('bb', {'b':2})]
>>> inquirer.list_input('Which?', carousel=True, choices=test)
[?] Which?: bb
   aa
 > bb

{'b': 2}
```

Whereas in 3.2.2 (and 3.2.3) doesn't:

```
>>> import inquirer
>>> test = [('aa', {'a': 1}), ('bb', {'b':2})]
>>> inquirer.list_input('Which?', carousel=True, choices=test)
[?] Which?:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "App/.venv/lib/python3.11/site-packages/inquirer/shortcuts.py", line 32, in list_input
    return render.render(question)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "App/.venv/lib/python3.11/site-packages/inquirer/render/console/__init__.py", line 38, in render
    return self._event_loop(render)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "App/.venv/lib/python3.11/site-packages/inquirer/render/console/__init__.py", line 49, in _event_loop
    self._print_hint(render)
  File "App/.venv/lib/python3.11/site-packages/inquirer/render/console/__init__.py", line 96, in _print_hint
    hint = render.get_hint()
           ^^^^^^^^^^^^^^^^^
  File "App/.venv/lib/python3.11/site-packages/inquirer/render/console/_list.py", line 23, in get_hint
    hint = self.question.hints[choice]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "App/.venv/lib/python3.11/site-packages/inquirer/questions.py", line 37, in __hash__
    return hash(self.tuple)
           ^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by Cube707** [comment] 2024-02-03 21:59
@Zereges this has nothing to do with the sting representation, please open a separate issue for this.
