### ISSUE TITLE
inquirer adding a lot to load time

### ISSUE THREAD

**Issue by t4styl** [magmax/python-inquirer#238] opened 2022-08-22 19:47 UTC
I'm currently working on replit, and am building a text game in python using inquirer. I declare all the questions in the functions when I use them, if that helps. However since changing to inquirer, I have noticed it takes about 7 seconds to load, when it previously only took about 1 or 2. You can check out the code [here](https://replit.com/@tastyl/lemon-collector) (Yes I know the code is terrible as I am quite a new developer, and this may partly be contributing to it, but it did increase a lot when I added inquirer). Thanks in advance!

**Comment by Cube707** [comment] 2022-08-22 21:01
I am sorry, but just No

You are using some arbitrary webaplication to run code I can't even get onto my system without making an account there, so I can't test or see anything that is going on. That's just nothing we can support.

In general inquire should not increase the startuptime by that mcuh, so it is most likely a configuration problem or some limitation of replit (maybe its your only thrid party app and it gets downloaded on startup?)

However, without a way to reproduce your issue in a sane way, I can't help you, sorry.

**Comment by Cube707** [comment] 2022-08-29 10:33
closing due to incativity and not reproducable

**Closed by Cube707** 2022-08-29 10:33 UTC
Labels: invalid
